unique_ids:
  assets:
    standard-page.html: JJGMLM3UMFO3MHP6XFTVMOD4FS5MV5VY
    theme.css: SHPFIKGNAHQIBEGHJOPPY5TJ2JLDXYWZ
  forms:
    Form1: M3PAS4B7QG42NIVPNAAQMJIZWVJKP4MG
  modules: {}
  scripts: {}
  server_modules: {}
